#spring.application.name=InterviewRights

jwt.secret=3u/MKRR+vCeIpgpeVV5a6Zo8N4EBhiv8mUA5pVsTDBCJzYm6O9YA+ZOVlx9zd95iYEVuPJ7z8whxCjRqjXKMMA==
jwt.expiration=86400000

# Database Configuration
spring.datasource.url=jdbc:mysql://mysqldb.c2j2i6qmglma.us-east-1.rds.amazonaws.com:3306/interview_rights
spring.datasource.username=appuser
spring.datasource.password=interviewRight@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Server Port
server.port=8080
app.base-url=http://interviewright-332017328.us-east-1.elb.amazonaws.com:8080

aws.access-key=
aws.secret-key=
aws.region=ap-southeast-2
aws.bucket-name=interview-right

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ept2658@gmail.com
spring.mail.password=kleguxqqnykbsmaq
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
